# Ligação à BD do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/estoque_db
spring.datasource.username=postgres
spring.datasource.password=2307

# JWT
api.security.token.secret=chave_secreta
api.security.web.config=frontend

# Hibernate - cria/atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true